name: Build, Push, and Deploy to Azure

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.PRREVIEWAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PRREVIEWAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PRREVIEWAPP_AZURE_SUBSCRIPTION_ID }}

      # This is the key missing step. It logs the Docker client into your ACR.
      - name: Log in to Azure Container Registry
        run: az acr login --name prreviewacr12345

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: prreviewacr12345.azurecr.io/pr-review-app:latest
          build-args: |
            HF_TOKEN=${{ secrets.HF_TOKEN }}
            GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}

      - name: Deploy new image to Container App
        run: |
          az containerapp update \
            --name pr-review-app \
            --resource-group pr-review-app-rg \
            --image prreviewacr12345.azurecr.io/pr-review-app:latest
