name: Build and Deploy PR-Review-App

on:
  push:
    branches:
      - master # Corrected to use your 'master' branch
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.PRREVIEWAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PRREVIEWAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PRREVIEWAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and Deploy to Azure Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          containerAppName: pr-review-app
          resourceGroup: pr-review-app-rg
          # --- THIS IS THE KEY FIX ---
          # Use the correct parameter 'containerAppEnvironment' with just the name
          containerAppEnvironment: pr-review-app-env
          registryUrl: prreviewacr12345.azurecr.io
          dockerfilePath: Dockerfile
          imageToBuild: prreviewacr12345.azurecr.io/pr-review-app:${{ github.sha }}
          buildArguments: |
            HF_TOKEN=${{ secrets.HF_TOKEN }}
            GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}
