name: Build and Deploy PR-Review-App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.PRREVIEWAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PRREVIEWAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PRREVIEWAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and Deploy to Azure Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          # This tells the action to look at the entire repository for source code
          appSourcePath: ${{ github.workspace }}
          # The name of your existing container app
          containerAppName: pr-review-app
          # The name of your resource group
          resourceGroup: pr-review-app-rg
          # The name of your existing container apps environment
          containerAppEnvironment: pr-review-env
          # The URL of your container registry
          registryUrl: prreviewacr12345.azurecr.io
          # The path to your Dockerfile
          dockerfilePath: Dockerfile
          # The full name and tag for the new image that will be built
          imageToBuild: prreviewacr12345.azurecr.io/pr-review-app:${{ github.sha }}
          # The required arguments to pass to the Docker build command
          buildArguments: |
            HF_TOKEN=${{ secrets.HF_TOKEN }}
            GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}
